# Generated by Django 3.2.7 on 2021-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('is_new', models.BooleanField(blank=True, null=True)),
                ('is_broken', models.BooleanField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, default=list, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('make', models.CharField(blank=True, max_length=128, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=128, null=True)),
                ('vin', models.CharField(blank=True, max_length=128, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=128, null=True)),
                ('drive', models.CharField(blank=True, max_length=128, null=True)),
                ('power', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads',
            },
        ),
    ]
