# Generated by Django 3.2.7 on 2021-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210904_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvertisement',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
