# Generated by Django 3.2.7 on 2021-09-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_caradvertisement_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caradvertisement',
            old_name='production_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='brand',
        ),
    ]
