# Generated by Django 3.2.7 on 2021-09-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210904_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caradvertisement',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='caradvertisement',
            name='is_broken',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caradvertisement',
            name='is_new',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
